# Content for the covering letter to the Industrial Registry (shared by the PDF and DOCX builders)
TITLE = "WC/2024/227 - Cory Lea Shepherd v Workers' Compensation Regulator"
TO = ["The Industrial Registrar", "Queensland Industrial Relations Commission", "qirc.registry@qirc.qld.gov.au",
      "Attention: Chambers of Commissioner Dwyer"]
CC = "Copy: Ms Renee Matheson, Senior Appeals Officer, Workers' Compensation Regulator (Renee.Matheson@oir.qld.gov.au)"
DATE = "[      ] October 2026"
SUBJECT = "Direction 5 election; application for leave to file a Second Amended Statement of Facts and Contentions (Form 9A); status of the documents"
BODY = [
("Direction 5.", "Under direction 5 of the Further Directions Order (3) of 19 August 2026, the Appellant elects a further conference under section 552A of the Workers' Compensation and Rehabilitation Act 2003, and asks that the application below be dealt with at or before it."),
("The application, and what the amendment does.", "The Appellant applies for leave to file and serve the enclosed Second Amended Statement of Facts and Contentions (Form 9A), under the Commission's power to give directions (Industrial Relations Act 2016, section 451(2)). The Respondent has been sent a copy and asked to consent. The amendment is made because the matter has crystallised since the Amended Form 9A of 7 April 2026: the Respondent admitted 298 of the 303 facts in the Appellant's notice of 28 August 2026, admitted or has since confirmed 29 of the 39 documents behind them, served its outlines of evidence on 24 September 2026, and has notified no medical or expert evidence. The Second Amended Form 9A accepts that the onus of proof is the Appellant's, withdraws the characterisations in the earlier pleading, confines each stressor to the admitted facts and the documents that record them, states the contentions and the questions for determination on that footing, and adds no new allegation. No hearing date has been set, so the amendment is sought before the matter is listed and before either party prepares for hearing on the earlier pleading. The Appellant does not oppose the Respondent having a period to amend its statement of facts and contentions if it wishes."),
("Why the document is the length it is.", "The enclosed pleading sets the admitted facts out under the stressor each proves, with the paragraph number of the admission against each, so that the whole case can be read in one document. Each stressor is pleaded so that it can be decided on its own; where a fact bears on more than one it is repeated, and the pleading says so. Part B.7 lists every document relied upon and its status; Part C states the contentions; Part D the questions for determination."),
("The matter, in summary.", "The Appellant was an Administration Officer (AO3) on the Logan Hospital Switchboard, a continuous 24/7 role whose function the Respondent admits is critical to patient safety (2, 13, 289). Stressor 1: from July 2023 database access was removed and not restored (40, 55), process changes were made effective the day they were notified without any listed record of consultation (51, 181, 273), calls were misdirected and the directory was not corrected (56 to 69, 89 to 110), and the manager's office hours were not stated for nine months (71 to 73); the Appellant's written request for them was met with a request to retract (74 to 77). Stressor 2: pay was wrong in four fortnights (185 to 189); Payroll's direction of 3 May 2024 was not actioned at 13 May (193), was still awaited on 21 May (195), and was lodged on 28 May and recorded \"Part Completed\" (203); a paid leave entitlement was declined twice on attachments the Respondent admits were present (116, 118, 134). Stressor 3: a seven-hour break was rostered between 17 and 18 March 2024 (284) against a minimum of ten hours or eight by written agreement (285), an agreement the employer's Human Resources says applied only to staff-initiated swaps, none being alleged (225, 234); the fatigue enquiry was answered after 23 days with a refusal (247, 249); no fatigue risk management existed at the Switchboard before 30 June 2024 (264, 269 to 271); and the Respondent's own review found the rostering was unreasonable management action (260) and employment a significant contributing factor (262). The Respondent's statement of facts and contentions identifies no management action relied upon for section 32(5) (303), and its outlines of evidence served 24 September 2026 notify no medical or expert evidence."),
("The record, available on request.", "The notice to admit facts (303 facts), the notice to admit documents (39 documents at Annexure A) and the Respondent's responses of 8 September 2026 were served between the parties and are not on the Commission's file. They, and the documents themselves, are available to the Commission on request: if the Commission wishes to consider them with the enclosure, the Appellant will file them in the form the Registry directs, together with the four documents the Respondent confirmed on 23 September 2026. The Appellant will proceed on whatever orders and directions the Commissioner gives on this application, on the documents, and on the further conduct of the appeal."),
("Where the Appellant stands.", "The Appellant relies on the admitted facts, the documents listed in the enclosed Part B.7, the treating medical records served on 9 September 2026, and the oral evidence of his treating general practitioner and psychiatrist. He does not rely on any medico-legal report. He seeks the orders in Part E of the enclosure."),
("The documents.", "The schedule on the following page states, for each of the 39 documents at Annexure A to the notices of 28 August 2026, whether its authenticity was admitted on 8 September 2026, disputed then and confirmed by the Respondent on 23 September 2026, or disputed and referred by the Respondent to Metro South Hospital and Health Service for copies. The facts recorded in every disputed document were admitted on 8 September 2026. The copies of the nine referred documents were produced from the Appellant's own records; five bear the signature of the employer's Director, Corporate Services. The Appellant asked the Respondent on 9 September 2026 to confirm them. Production of the same documents by Metro South to the Respondent, and their disclosure back to the Appellant, would return to him documents he already holds. The Appellant asks that the Respondent be directed to state, by a date the Commission fixes, whether it disputes the authenticity of each of the ten outstanding documents and on what ground; failing which, that they be received at hearing subject to proof."),
]
SCHEDULE_TITLE = "Schedule: the documents at Annexure A (notices to admit served 28 August 2026)"
SCHEDULE = [
("Admitted, 8 September 2026 (25)", [
 "1A Stibbard, \"Hello & Update\", 18 Jul 2023", "1B Taylor to Reese, \"Fwd: Communication Book Update\", 6 Jun 2023", "2 \"Increase of hours and Workplace issues\" chain, 7-10 Aug 2023", "3 Reese, HR Policy E12 and emails, 29 Aug-8 Sep 2023", "4 \"Request to Increase Working Hours\" and emails, 7 and 31 Aug 2023", "7 \"Roster Concerns\" chain, 26 Apr-8 May 2024", "8 Reese to Pritchard and to LBH_HR, 10 and 20 May 2024", "8A QH-GDL-401-3.3 cover page, 2021", "8B MASPER emails and issue logs, 2-9 May 2024", "8C Stibbard on-call email, 13 May 2024", "9 \"Switchboard Manager - On call and Hours.\", 17 May 2024", "9A \"Office Hours and Departmental Directives\" chain, 15 May 2024", "9B Reese reply, 21 May 2024", "10 \"Sick leave 14.05.24\" and forwarding, 14-15 May 2024", "11 Integrated Respiratory Service emails and replies, 15 and 20 May 2024", "12 \"Corey Shepherd 388372 Pay issues\", 3-13 May 2024", "13 Same thread, 21 May 2024", "14 \"Validation of Claims older than 3 months\", 28 May 2024", "15 myHR submissions report, 1 Feb-31 May 2024", "16 Leave Takings Report, 19 Mar 2024", "25 Review Decision 69983, 24 Oct 2024", "26 Appellant's first notice to admit facts", "27 Respondent's response, 18 Feb 2026", "28 myHR leave request history 15480560, 20 Feb-1 Mar 2024", "29 Instrument of Sub-Delegation, eff. 5 Dec 2022"]),
("Disputed 8 September 2026; confirmed by the Respondent 23 September 2026 (4)", [
 "6 Taylor, \"Afterhours Oncall Process - Switchboard\", 15 Apr 2024", "20 Metro South to Commissioner Dwyer, K-LM26/729, 5 Jun 2026", "30 Taylor, \"What's Chloe's Hours?!\", 23 Aug 2023", "30A Taylor, \"Good morning Team.\", 18 Jun 2024"]),
("Disputed 8 September 2026; referred by the Respondent to Metro South 23 September 2026 (9) - contents admitted at the facts shown", [
 "1 Role description, AO3 Switchboard Services, undated (facts 1-13)", "5 Taylor, \"Approved - Permanent Full Time FTE\", 27 Sep 2023 (37-38)", "17, 18, 19 Movement forms signed by Mr Hughes, 27 Feb, 17 Apr, 9 Jun 2026 (14-15)", "21 Forrest (HR) to the Appellant, 7 Jul 2026 (224-225)", "22 Consultation Paper, Proposed Rosters, signed by Mr Hughes 12 Nov 2024 (169-175)", "23 Consultation outcome, signed by Mr Hughes 12 Dec 2024 (167-168, 176-177)", "31 \"2024 Emergency Code Register\", March 2024 sheet, 16-20 Mar 2024 (228-231 not admitted)"]),
("Disputed 8 September 2026; not addressed by the Respondent on 23 September 2026 (1)", [
 "24 Moran (Together Queensland), \"Switchboard Roster Feedback - For Delegates\", 3 Nov 2025 (178-179)"]),
]
CLOSE = ["The Appellant asks that this letter and its enclosure be placed before Commissioner Dwyer and will proceed on the orders made.", "Cory Lea Shepherd", "Appellant, self-represented"]
