# Content for the covering letter to the Industrial Registry (shared by the PDF and DOCX builders)
TITLE = "WC/2024/227 - Cory Lea Shepherd v Workers' Compensation Regulator"
TO = ["The Industrial Registrar", "Queensland Industrial Relations Commission", "qirc.registry@qirc.qld.gov.au",
      "Attention: Chambers of Commissioner Dwyer"]
CC = "Copy: Ms Renee Matheson, Senior Appeals Officer, Workers' Compensation Regulator (Renee.Matheson@oir.qld.gov.au)"
DATE = "30 September 2026"
SUBJECT = "Direction 5 election; application for leave to file a Second Amended Statement of Facts and Contentions (Form 9A); status of the documents"
BODY = [
("Direction 5.", "Under direction 5 of the Further Directions Order (3) of 19 August 2026, the Appellant elects a further conference under section 552A of the Workers' Compensation and Rehabilitation Act 2003, and asks that the application below be dealt with at or before it."),
("The application, and what the amendment does.", "The Appellant applies for leave to file and serve the enclosed Second Amended Statement of Facts and Contentions (Form 9A), under the Commission's power to give directions (Industrial Relations Act 2016, section 451(2)). A copy goes to the Respondent with this letter, and its consent is sought. The amendment is sought because the matter has become much clearer since the Amended Form 9A of 7 April 2026. The Respondent has admitted 298 of the 303 facts in the Appellant's notice of 28 August 2026. It has admitted, or has since confirmed, 29 of the 39 documents behind them. The Second Amended Form 9A accepts that the onus of proof is on the Appellant, withdraws the descriptions of conduct used in the earlier pleading, confines each stressor to the admitted facts and the documents that record them, states the contentions and the questions for decision on that footing, and adds no new allegation. No hearing date has been set, so the amendment is sought before the matter is listed and before either party prepares for hearing on the earlier pleading. The Appellant does not oppose the Respondent having time to amend its own statement of facts and contentions if it wishes. The pleading sets out the admitted facts under the stressor each one proves, with the paragraph number of the admission against each, so that the whole case can be read in one document. Each stressor is pleaded so that it can be decided on its own; where a fact matters to more than one stressor it is repeated, and the pleading says so. The schedule to this letter lists the documents relied on, other than the treating medical records served on 9 September 2026, and their status."),
("The matter, in summary.", "The Appellant was an Administration Officer (AO3) on the Logan Hospital Switchboard, a continuous 24/7 role whose function the Respondent admits is critical to patient safety (2, 13, 289). Stressor 1: from July 2023 database access was removed and not restored (40, 55); process changes were made effective the day they were notified, with no listed record of consultation (51, 181, 273); calls were misdirected and the directory was not corrected (56 to 69, 89 to 110); the manager's office hours were not stated for nine months (71 to 73); and the Appellant's written request for them was met with a request to retract (74 to 77). Stressor 2: pay was wrong in four fortnights (185 to 189); Payroll's direction of 3 May 2024 was not actioned at 13 May (193), was still awaited on 21 May (195), and was lodged on 28 May and recorded \"Part Completed\" (203); a paid leave entitlement was declined twice on attachments the Respondent admits were present (116, 118, 134). Stressor 3: a seven-hour break was rostered between 17 and 18 March 2024 (284) against a minimum of ten hours, or eight by written agreement (285), an agreement the employer's Human Resources says applied only to staff-initiated swaps, none being alleged (225, 234); the fatigue enquiry was answered after 23 days with a refusal (247, 249); no fatigue risk management existed at the Switchboard before 30 June 2024 (264, 269 to 271); and the Respondent's own review found the rostering was unreasonable management action (260) and employment a significant contributing factor (262). The Respondent's statement of facts and contentions identifies no management action relied on for section 32(5) (303)."),
("The Respondent's evidence.", "Directions 3 and 4 of the Further Directions Order (3) required the Respondent's list of witnesses, its outlines of evidence and any expert reports that will be relied upon by 4.00 pm on 30 September 2026. On 24 September 2026 it sent its list to the Registry for filing, naming four witnesses, Ms Taylor, Ms Reese, Ms Wright and Ms Earl, described as \"lay\" witnesses, and served outlines of their evidence. Neither the list nor the outlines names a medical or expert witness, and no expert report has been served as at the date of this letter. The Respondent's amended statement of facts and contentions of 13 May 2026 does not admit the pleaded onset and diagnosis of the injury, saying these are \"matters for determination by the Commission at a hearing\" (paragraph 9), and identifies no expert evidence. Its response of 8 September 2026 to the notices to admit names no medical or expert witness, and the documents listed under the headings \"Medical Certificates\" and \"Medical\" in its amended List of Documents of 14 August 2026 are those of the treating practitioners (items 7 to 11)."),
("The record, available on request.", "The notice to admit facts (303 facts), the notice to admit documents (39 documents at Annexure A) and the Respondent's responses of 8 September 2026 were served between the parties and are not on the Commission's file. They, and the documents themselves, are available to the Commission on request. If the Commission wishes to consider them with the enclosure, the Appellant will file them in the form the Registry directs, together with the four documents the Respondent confirmed on 23 September 2026. The Appellant will proceed on whatever orders and directions the Commissioner gives on this application, on the documents, and on the further conduct of the appeal."),
("Where the Appellant stands.", "The Appellant relies on the admitted facts, the documents in the schedule to this letter, the treating medical records served on 9 September 2026, and the oral evidence of his treating general practitioner and psychiatrist. No medico-legal report is relied on. His list of witnesses filed, and his outlines of evidence served, on 9 September 2026 under directions 1 and 2 are not changed by the amendment. He seeks the orders in Part E."),
("The documents.", "Part 1 of the schedule on the following pages states the status of each of the 39 documents at Annexure A to the notices of 28 August 2026; Part 2 lists the other documents the pleading relies on. The Appellant asks that the Respondent be directed to state, by a date the Commission fixes, whether it disputes the authenticity of each of the ten outstanding documents and on what ground; and that, if it does not, they be received at hearing subject to proof."),
]
SCHEDULE_TITLE = "Schedule, Part 1: the 39 documents at Annexure A (notices to admit served 28 August 2026) and their status"
PART1_INTRO = "The 39 documents at Annexure A to the notices to admit served 28 August 2026 are the documents from which the facts in Part B of the Second Amended Form 9A are drawn. On 8 September 2026 the Respondent admitted the authenticity of 25 of them and disputed 14. By email of 23 September 2026 it confirmed four of the 14 \"upon further review of the appeal file\", stated that it had \"requested copies of these documents to be disclosed from MSH\" for nine others, and did not mention the fourteenth. The facts recorded in 13 of the 14 were admitted on 8 September 2026 to the extent set out in Part B; the exception is the register at Tab 31, from which facts 228 to 231 were not admitted. For the other 13, what remains in dispute is the authenticity of the copies, not their content."
SCHEDULE_COLS = ["Tab", "Document", "Date", "8 Sep 2026", "23 Sep 2026", "Position now"]
A="Admitted"; D="Disputed"; C="Confirmed by the Respondent"; M="Referred by the Respondent to Metro South for copies"; N="Not mentioned"
SCHEDULE_ROWS = [
 ("1A","Stibbard to the Switchboard team, \"Hello & Update\"","18 Jul 2023, 12:56 pm",A,"-","Admitted; tender"),
 ("1B","Taylor to Reese, \"Fwd: Communication Book Update\", with her email to Logan Switch of 9:57 am that day","6 Jun 2023, 4:05 pm",A,"-","Admitted; tender"),
 ("2","\"Increase of hours and Workplace issues\" chain and Reese's replies","7-10 Aug 2023",A,"-","Admitted; tender"),
 ("3","Reese attaching HR Policy E12; emails of 4 and 8 Sep 2023","29 Aug-8 Sep 2023",A,"-","Admitted; tender"),
 ("4","\"Request to Increase Working Hours to Full Time Rotational Roster\"; emails of 7 Aug 2023 1:43 pm and 5:11 pm","7 and 31 Aug 2023",A,"-","Admitted; tender"),
 ("7","\"Roster Concerns\" chain","26 Apr-8 May 2024",A,"-","Admitted; tender"),
 ("8","Reese to Pritchard \"FW: Roster Concerns\"; Reese to LBH_HR attaching qh-gdl-401-3.3","10 and 20 May 2024",A,"-","Admitted; tender"),
 ("8A","Cover page, Fatigue risk management systems implementation guideline QH-GDL-401-3.3:2021","2021",A,"-","Admitted; tender"),
 ("8B","MASPER emails (Taylor to Kwok and Wong; \"MASPER process\") and issue logs","9 May 2024 (logs 2-8 May)",A,"-","Admitted; tender"),
 ("8C","Stibbard, \"Switchboard After Hours On Call Manager PP24\"","13 May 2024, 4:29 pm",A,"-","Admitted; tender"),
 ("9","Taylor, \"Switchboard Manager - On call and Hours.\"","17 May 2024, 9:30 am",A,"-","Admitted; tender"),
 ("9A","\"Office Hours and Departmental Directives\" chain (1:15 pm, 6:23 pm, 7:09 pm)","15 May 2024",A,"-","Admitted; tender"),
 ("9B","Reese, \"RE: Office Hours and Departmental Directives\"","21 May 2024, 2:53 pm",A,"-","Admitted; tender"),
 ("10","Taylor, \"Sick leave 14.05.24\", and its forwarding to Reese","14-15 May 2024 (first email 14 May, 12:08 pm)",A,"-","Admitted; tender"),
 ("11","Marriott (Integrated Respiratory Service) to Logan Switch; the Appellant to Taylor; Taylor's reply","15 and 20 May 2024",A,"-","Admitted; tender"),
 ("12","\"Corey Shepherd 388372 Pay issues\" thread","3-13 May 2024",A,"-","Admitted; tender"),
 ("13","Same thread, Taylor to the Appellant","21 May 2024, 12:33 pm",A,"-","Admitted; tender"),
 ("14","Taylor, \"Validation of Claims older than 3 months - Please sign\"","28 May 2024, 8:36 am",A,"-","Admitted; tender"),
 ("15","myHR submissions report (MSH Item 11)","1 Feb-31 May 2024",A,"-","Admitted; tender"),
 ("16","QH Leave Takings Report (MSH Item 15)","19 Mar 2024",A,"-","Admitted; tender"),
 ("25","Review Decision 69983","24 Oct 2024",A,"-","Admitted; tender"),
 ("26","Appellant's first notice to admit facts","before 18 Feb 2026",A,"-","Admitted; tender"),
 ("27","Respondent's response to that notice","18 Feb 2026",A,"-","Admitted; tender"),
 ("28","myHR leave request history, Process Reference 15480560 (MSH Item 11)","20 Feb-1 Mar 2024",A,"-","Admitted; tender"),
 ("29","Instrument of Human Resource Sub-Delegation, Paid Special Pandemic Leave (MSH Item 13)","eff. 5 Dec 2022",A,"-","Admitted; tender"),
 ("6","Taylor, \"Afterhours Oncall Process - Switchboard\" (Stressor 1(c))","15 Apr 2024, 12:39 pm",D,C,"Now admitted; tender"),
 ("20","Metro South to Commissioner Dwyer, K-LM26/729, signed by the Chief Executive (Stressors 1(f) and 3(i))","5 Jun 2026",D,C,"Now admitted; tender"),
 ("30","Taylor, \"What's Chloe's Hours?!\" (Stressor 1(b))","23 Aug 2023, 2:18 pm",D,C,"Now admitted; tender"),
 ("30A","Taylor, \"Good morning Team.\" (Stressor 1(b))","18 Jun 2024, 8:58 am",D,C,"Now admitted; tender"),
 ("1","Role description, Administration Officer, Switchboard Services (AO3), Logan Hospital","undated",D,M,"Outstanding; contents admitted (facts 1-13)"),
 ("5","Taylor, \"Approved - Permanent Full Time FTE\"","27 Sep 2023, 1:52 pm",D,M,"Outstanding; contents admitted (37-38)"),
 ("17","Movement form, approved by Mr Hughes as delegate, recording \"Continuous Shift Worker\"","27 Feb 2026",D,M,"Outstanding; contents admitted (14-15)"),
 ("18","Movement form, approved by Mr Hughes, recording \"Continuous Shift Worker\"","17 Apr 2026",D,M,"Outstanding; contents admitted (14-15)"),
 ("19","Movement form, approved by Mr Hughes, recording \"Continuous Shift Worker\"","9 Jun 2026",D,M,"Outstanding; contents admitted (14-15)"),
 ("21","Forrest, Senior Consultant Human Resources, to the Appellant, stating that the 8-hour agreement \"is only applied where staff initiated shift swaps have occurred\"","7 Jul 2026",D,M,"Outstanding; contents admitted (224-225)"),
 ("22","Consultation Paper, Proposed Rosters for Switchboard Services, signed by Mr Hughes 12 Nov 2024","Nov 2024",D,M,"Outstanding; contents admitted (169-175)"),
 ("23","Consultation outcome, Proposed Rosters, signed by Mr Hughes 12 Dec 2024","Dec 2024",D,M,"Outstanding; contents admitted (167-168, 176-177)"),
 ("31","Screen capture, \"2024 Emergency Code Register.xlsx\", March 2024 sheet, entries 16-20 Mar 2024 (Stressor 3(e))","Mar 2024",D,M,"Outstanding; facts 228-231 not admitted"),
 ("24","Moran, Organiser, Together Queensland, to Jeffrey, Conaghan and the Appellant, \"Switchboard Roster Feedback - For Delegates\"","3 Nov 2025",D,N,"Outstanding; contents admitted (178-179)"),
]
PART2_TITLE = "Schedule, Part 2: other documents relied on in the Second Amended Form 9A that are not at Annexure A"
PART2_COLS = ["Document", "Relied on at", "Status or source"]
PART2_ROWS = [
 ("The Respondent's outlines of the evidence of Ms Taylor, Ms Reese, Ms Wright and Ms Earl","Stressors 1(j), 2(a), 3(a) and 3(f); Part C, paragraph 5A","Served by the Respondent on 24 September 2026; available to the Commission on request. An outline is not evidence."),
 ("The spreadsheet of recorded MET calls for 17 and 18 March 2024","Stressor 3(e)","Metro South Health states that it is available [\u00b6 268]."),
 ("The Logan Hospital emergency code procedures referred to in the role description","Stressor 3(e)(i)","Referred to in the role description [\u00b6 8] (Tab 1)."),
 ("The documents recording the advice of Human Resources on the 8-hour agreement","Referred to in the outlines (first row)","The outlines of Ms Taylor and Ms Reese refer to them; neither identifies them."),
 ("The Communication Book","Stressor 1(g); Part B.5.4","Not listed in the Respondent's amended List of Documents of 14 August 2026; paragraph 154 of the notice was not admitted."),
 ("The Respondent's disclosure of July 2025 headed \"Disclosure from witness conferencing - Qld Health Payroll\" (24 pages): the email of Ms Christensen, Manager Service Delivery, Payroll, to the Respondent of 11 July 2025, and Payslips 01 to 07, including Payslip 06 (pay date 5 June 2024) and Payslip 07 (pay date 2 July 2025)","Stressor 2(a); Part B.4","Disclosed by the Respondent in July 2025."),
 ("The Respondent's disclosure of 11 June 2026 (10 pages): the leave-form walkthrough for Process Reference 15480560, the emails of 15 May 2024 at 1:15 pm and 6:23 pm, the emails of 15 and 16 May 2024 concerning the complaint of 13 May 2024, and the complaint form","Stressor 1(j), for dates, senders and recipients only","Disclosed by the Respondent on 11 June 2026."),
 ("Queensland Health's Code Blue procedure 001443 (Royal Brisbane and Women's Hospital, version 5, April 2020)","Stressor 3(e)(i): the types of Code Blue and the role of Switchboard Services","Public document."),
 ("The Queensland Ombudsman's Neville Report (June 2006) and its 2011 update, and the Coroner's findings of 12 September 2008","Stressor 3(i): the origin of the fatigue framework","Public documents."),
 ("The monthly call statistics for April 2025","Stressor 3(e)(v)","The Appellant's own record and evidence (Part B preamble)."),
]
SCHEDULE_NOTE = "The Appellant asked the Respondent on 9 September 2026 to confirm the ten outstanding documents. The Respondent's email of 23 September 2026 gives no date by which the copies are expected, and does not refer to Tab 24, which is a Together Queensland document, not a Metro South Health document. The nine documents the Respondent referred to Metro South Health are Metro South Health documents. The copies of Tabs 1, 5, 17 to 19, 21 to 24 and 31 came from the Appellant's own records; Tabs 17 to 19, 22 and 23 bear the signature of the employer's Director, Corporate Services. If Metro South produces the same documents to the Respondent, and the Respondent discloses them back to the Appellant, he will receive documents he already holds. This letter accompanies the Appellant's election and requested directions (one page). Enclosure: Second Amended Statement of Facts and Contentions (Form 9A), {PAGES} pages."
CLOSE = ["The Appellant asks that this letter and its enclosure be placed before Commissioner Dwyer and will proceed on the orders made.", "Cory Lea Shepherd, Appellant (self-represented)"]
