exec(open('edit_change95.py').read())
d=Doc('2026-10_SECOND_AMENDED_9A_FINAL.docx'); R=d.rep
R("that no document records consultation with Switchboard operators before the 15 April 2024 change;","that its List of Documents lists no document recording consultation with Switchboard operators before the 15 April 2024 change;")
R("[Tabs M6, M8 and M9.]","[Tabs M2, M8 and M9.]")
R("The codes. The position receives emergency response notifications and distributes them to the appropriate response groups, dependent on the category of emergency, as per emergency code procedures, strictly adhering to protocols and timeframes. [¶ 8] ","The codes. ")
R("database access was removed and not restored [¶¶ 40, 55]","database access was removed and not alleged to have been restored [¶¶ 40, 55]")
R("Database access removed and not restored;","Database access removed, with no restoration alleged;")
R("Operators' access to the database removed and not restored;","Operators' access to the database removed, with no restoration alleged;")
R("The Respondent does not allege that fixed office hours were stated to the Switchboard staff at any time","The Respondent does not allege that the Manager stated fixed office hours to the Switchboard staff at any time")
R("5.3 As to the office hours. That fixed office hours were stated to the Switchboard staff","5.3 As to the office hours. That the Manager stated fixed office hours to the Switchboard staff")
R("The Respondent does not allege that the toolkit was reviewed or that any feedback was provided before 18 June 2024. [¶ 216]","The Respondent does not allege that the Manager reviewed the toolkit or provided any feedback on it before 18 June 2024. [¶ 216]")
R("that the fatigue toolkit was reviewed or feedback given before 18 June 2024;","that the Manager reviewed the fatigue toolkit or gave feedback on it before 18 June 2024;")
R("held that role, and never reviewed;","held that role, and not alleged to have been reviewed before 18 March 2024;")
R("ceased to be in its possession during his employment.","ceased to be in the possession of Metro South Health during his employment.")
R("that any response was made to the Integrated Respiratory Service before 20 May 2024, or before 2:05 pm on that day;","that any response was made to the Service's email of 15 May 2024 before 20 May 2024, or to its email of 20 May 2024 before 2:05 pm on that day;")
R("would not be processed [¶ 247]; the review decision records that payroll was, as at 1 May 2024, still reviewing his public holiday entitlements. [¶ 255]","would not be processed. [¶ 247]")
R('As at 1 May 2024 payroll was "still reviewing your entitlements','The review decision records that, as at 1 May 2024, payroll was "still reviewing your entitlements')
R("says that they are not relevant because","says that this fact is not relevant because")
R('was implemented only "after 30 June 2024"','was implemented "after 30 June 2024"')
R("that any other means of notification was required. [¶ 166]","that notifying his unavailability by telephoning the Switchboard did not comply with the process required of him. [¶ 166]")
d.save(); print("ok")
