exec(open('edit_change68.py').read().split("CAUSAL=")[0])
def set_body(d,key,new,contains=None):
    """keep the first run if it is a label/number; put `new` in the next text run; drop later text runs"""
    p=d.para(key,contains)
    runs=re.findall(r'<w:r>.*?</w:r>|<w:r .*?</w:r>',p,re.S)
    truns=[r for r in runs if '<w:t' in r]
    t0=html.unescape(re.search(r'<w:t[^>]*>([^<]*)</w:t>',truns[0]).group(1))
    lab = ('<w:b/>' in truns[0] or re.match(r'^\d+\.$',t0.strip())) and len(truns)>1
    body=truns[1] if lab else truns[0]
    rest=truns[2:] if lab else truns[1:]
    np_=p.replace(body,re.sub(r'<w:t[^>]*>[^<]*</w:t>','<w:t xml:space="preserve">'+esc(new)+'</w:t>',body),1)
    for r in rest: np_=np_.replace(r,'',1)
    assert d.x.count(p)==1; d.x=d.x.replace(p,np_)
def insert_after(d,anchor_key,template_key,label,body,anchor_contains=None):
    a=d.para(anchor_key,anchor_contains); t=d.para(template_key)
    runs=[r for r in re.findall(r'<w:r>.*?</w:r>|<w:r .*?</w:r>',t,re.S) if '<w:t' in r]
    new=t.replace(runs[0],re.sub(r'<w:t[^>]*>[^<]*</w:t>','<w:t xml:space="preserve">'+esc(label)+'</w:t>',runs[0]),1)
    new=new.replace(runs[1],re.sub(r'<w:t[^>]*>[^<]*</w:t>','<w:t xml:space="preserve">'+esc(body)+'</w:t>',runs[1]),1)
    for r in runs[2:]: new=new.replace(r,'',1)
    assert d.x.count(a)==1; d.x=d.x.replace(a,a+new)

# ================= ELECTION =================
e=Doc('2026-10_REQUEST_election_and_directions_FINAL.docx')
set_body(e,'2.That, at the opening',"That, at the opening of the conference, the Respondent state whether it maintains the contention in paragraph 27 of its amended statement of facts and contentions of 13 May 2026 and, if it does, that the contention be particularised in accordance with direction 5 below.")
set_body(e,'3.That the Appellant have leave',"That the proposed Second Amended Statement of Facts and Contentions (Form 9A) enclosed with the Appellant's letter be considered for the purposes of the application for leave and, if leave is granted under section 451(2) of the Industrial Relations Act 2016, that the Appellant be permitted to file and serve it. The proposed Form 9A accepts that the Appellant bears the onus of proof, retains the three stressors, and sets out their particulars by dated event against the facts admitted on 8 September 2026. It adds no new stressor or allegation. The Appellant's list of witnesses filed, and outlines of evidence served, on 9 September 2026 are not amended and stand as filed and served.")
set_body(e,'4.That the Respondent state',"That the Respondent state, by 4.00 pm on a date fixed by the Commission, whether it maintains its dispute as to the authenticity of each of the ten documents at Annexure A to the Appellant's notice to admit documents served 28 August 2026 that remain outstanding and, for each dispute maintained, particularise the ground on which authenticity is disputed; being Tabs 1, 5, 17, 18, 19, 21, 22, 23 and 31, of which the Respondent said on 24 September 2026 that it had requested copies from Metro South Hospital and Health Service, and Tab 24, which its email of that date did not address. The facts recorded in each, other than the register at Tab 31 (facts 228 to 231), were admitted on 8 September 2026. The Appellant asks that any dispute not so maintained cease to be in issue, and that the Appellant have liberty to apply in relation to any authenticity dispute remaining after that date. No direction as to relevance, weight or admissibility is presently sought.")
set_body(e,'5.That the Respondent state',"That the Respondent state, for each causal particular in the proposed Second Amended Form 9A, namely 1(b), 1(d), 1(f) to 1(h), 1(k) and 1(l); 2(a) to 2(i), 2(l) and 2(m); and 3(b) to 3(f), whether it contends that the particular was management action and, if so, the facts on which it relies to say that the action was reasonable and taken in a reasonable way, by the date fixed for any amended statement of facts and contentions under 6 below. The other particulars are context, or the record of how the matters were handled, and no answer is sought on them.")
set_body(e,'6.That the Respondent have leave',"That, if leave is granted and the Second Amended Form 9A is filed, the Respondent have leave to file and serve an amended statement of facts and contentions, and any amended list of witnesses and outlines of evidence, if it wishes, within 14 days after that filing.")
set_body(e,'Enclosed with this page',"Enclosed with this page: the Appellant's letter of explanation, with the schedule of the documents relied on and their status and an index of the particulars; and the proposed Second Amended Statement of Facts and Contentions (Form 9A), provided for the Commission's consideration of the application for leave. The notices to admit, the Respondent's responses and the documents themselves are available to the Commission on request.")
e.save()

# ================= LETTER =================
l=Doc('2026-10_LETTER_to_Registry_FINAL.docx')
l.rep('Direction 5 election; application for leave','Second Amended Statement of Facts and Contentions (Form 9A)','proposed Second Amended Statement of Facts and Contentions (Form 9A)')
set_body(l,'The application.',"The Appellant was an Administration Officer on the Logan Hospital Switchboard; the Respondent admits that maintaining accurate contact details for medical staff is a critical function of the Switchboard to ensure effective clinical handover and patient safety (fact 289). The Appellant applies for leave under section 451(2) of the Industrial Relations Act 2016 to file and serve the proposed Second Amended Statement of Facts and Contentions (Form 9A) enclosed for the Commission's consideration. A copy is provided to the Respondent with this letter and its consent is sought. Since the Amended Form 9A of 7 April 2026, the Respondent has admitted, to the extent recorded in its response of 8 September 2026, 298 of the 303 facts in the Appellant's notice of 28 August 2026, and has admitted or since confirmed 29 of the 39 documents behind them. The proposed amendment accepts that the onus of proof is on the Appellant, withdraws the descriptions of conduct used in the earlier pleading, and adds no new stressor or allegation. No hearing date has been set. The Appellant does not oppose the Respondent having time to amend its own statement of facts and contentions if leave is granted. The Appellant's list of witnesses filed, and outlines of evidence served, on 9 September 2026 are not amended and stand as filed and served.")
insert_after(l,'The application.','The record, available on request.','How the proposed Form 9A is arranged. ',"Each of the three stressors is pleaded so that it can be read and assessed on its own facts. An admitted fact is repeated where necessary to keep each stressor's sequence complete and to show the different part it plays there; read together, the three stressors show the whole course of employment circumstances relied on. Under each stressor, the list of stressors identifies the individual events relied on as causes; the other particulars are context, or the employer's record of how the matters were handled. The treating records are used for what was recorded clinically about that course and its effect, not to prove a disputed workplace event.")
set_body(l,'The record, available on request.',"The notices to admit, the Respondent's responses of 8 September 2026 and the underlying documents were served between the parties and are available to the Commission in the form the Registry directs.")
set_body(l,'The documents.',"Part 1 of the schedule on the following pages states the status of each of the 39 documents at Annexure A to the notices of 28 August 2026; Part 2 lists the other documents the pleading relies on; Part 3 indexes the dated particulars of the proposed Second Amended Form 9A and adds no stressor. The Appellant asks that the Respondent be directed, by a date fixed by the Commission, to state whether it maintains its dispute as to the authenticity of each of the ten outstanding documents and, for each dispute maintained, particularise the ground on which authenticity is disputed; that any dispute not so maintained cease to be in issue; and that the Appellant have liberty to apply in relation to any authenticity dispute remaining after that date. No direction as to relevance, weight or admissibility is presently sought.")
l.delete('The Appellant asks that this letter and its enclosure be placed before Commissioner Dwyer')
insert_after(l,'The documents.','The record, available on request.','Filing position. ',"The Appellant asks that the election and this letter be filed and placed before Commissioner Dwyer. The proposed Second Amended Form 9A is enclosed only for the Commission's consideration of the application for leave and is not presently submitted for filing. If leave is granted, the Appellant will supply a hard copy of the Form 9A to the Registry and will file and serve it in the form directed by the Commission or Registry.")
set_body(l,'This letter accompanies',"This letter accompanies the Appellant's election and requested directions. Enclosure for consideration: proposed Second Amended Statement of Facts and Contentions (Form 9A).")
# schedule: 24 September (AEST) and "proposed"
l.rep('The 39 documents at Annexure A','in Part B of the Second Amended Form 9A','in Part B of the proposed Second Amended Form 9A')
l.rep('The 39 documents at Annexure A','By email of 23 September 2026','By email of 24 September 2026')
l.x=l.x.replace('>23 Sep 2026<','>24 Sep 2026<')
l.rep('The Appellant asked the Respondent on 9 September 2026',"email of 23 September 2026 gives no date","email of 24 September 2026 gives no date")
l.rep('The Appellant asked the Respondent on 9 September 2026',"which the email of 23 September 2026 does not address","which the email of 24 September 2026 does not address")
l.rep('Schedule, Part 2:','in the Second Amended Form 9A','in the proposed Second Amended Form 9A')
l.rep('Schedule, Part 3:','index of the dated particulars in the Second Amended Form 9A','index of the dated particulars in the proposed Second Amended Form 9A')
l.rep('Schedule, Part 3:','with their particulars, in the Second Amended Form 9A;','with their particulars, in the proposed Second Amended Form 9A;')
l.rep('Schedule, Part 3:','list of stressors in the Second Amended Form 9A.','list of stressors in the proposed Second Amended Form 9A.')
l.rep('Stressor 3(b), the ordinary-call-load paragraph','Stressor 3(b), the ordinary-call-load paragraph','Stressor 1, the operating conditions; Stressor 3(b), the ordinary-call-load paragraph')
# Part 2: full guideline row
t2=[t for t in re.findall(r'<w:tbl>.*?</w:tbl>',l.x,re.S) if 'Relied on at' in t][0]
rows=re.findall(r'<w:tr[ >].*?</w:tr>',t2,re.S); tmpl=rows[-1]
cells=re.findall(r'<w:tc>.*?</w:tc>',tmpl,re.S); nr=tmpl
for c,v in zip(cells,["Queensland Health Fatigue Risk Management Systems Implementation Guideline QH-GDL-401-3.3:2021 (the full disclosed guideline)","Stressor 3(h) and the supporting fatigue records; the quotations from the guideline","Disclosed in full with the 20 May 2024 email chain on 14 July 2025. Tab 8A at Annexure A is the cover page only."]):
    nr=nr.replace(c,re.sub(r'<w:t[^>]*>[^<]*</w:t>','<w:t xml:space="preserve">'+esc(v)+'</w:t>',c,count=1),1)
nr=re.sub(r'(<w:tc>.*?)(<w:t xml:space="preserve">[^<]*</w:t>)(.*?</w:tc>)',lambda m:m.group(0),nr)
l.x=l.x.replace(t2,t2.replace(tmpl,tmpl+nr))
# Part 3 row 2(e)
l.rep('Payroll later described the claim as submitted late.','Payroll later described the claim as submitted late.',"Payroll later described the 30 March public holiday claim as submitted late; relied on as Payroll's later account, not as an admission.")
l.save()

# ================= 9A =================
d=Doc('2026-10_SECOND_AMENDED_9A_FINAL.docx')
d.rep('Each fact set out below that carries a paragraph number','the register at Tab 31, the call statistics and the account of travel and sleep in Stressor 3 are of that kind,',
 'the register at Tab 31, the call statistics, the account of the operating conditions in Stressor 1 and the account of travel and sleep in Stressor 3 are of that kind,')
d.rep('1.9 The medical evidence at hearing.','No medico-legal report has been, or will be, prepared for this proceeding.','No medico-legal report has been prepared for this proceeding.')
d.rep('Database access removed and not restored;','Particulars 1(a) to 1(l); the causal particulars are listed below.','All of this in a role carrying high call volume, concurrent emergency codes and complaints arriving first at the Switchboard. Particulars 1(a) to 1(l); the causal particulars are listed below.')
OC1=("The Appellant's evidence is that he handled several hundred calls on a shift, a substantial proportion of them from people who were distressed, frightened, in conflict or in crisis, and that he was often the first person a caller reached in an urgent situation; that he triaged and connected those calls, identifying which could not wait and routing each to the correct clinician or team while continuing to answer the queue; that he relayed urgent pathology and other clinical results between doctors; and that, when a caller in an emergency could not say where they were, he had to identify the source and location of the call so that help could be sent to the right place. The monthly call statistics for April 2025 record between 269 and 444 calls on an eight-hour shift (Stressor 3(b)).")
OC2=("Emergency codes are received at the Switchboard, categorised by the operator by the type of emergency, and paged to the response group for that category within the time the procedure allows. [¶ 8] The Appellant's evidence is that each code was paged at the same time to a response team of about ten clinicians through the SPOK paging system; that codes and other urgent matters did not arrive one at a time, so that he managed concurrent emergency and security responses and time-critical clinical calls while continuing to manage the call queue; and that the number of codes varied from day to day. The Emergency Code Register records eight codes on 17 March 2024, eleven on 18 March and sixteen entries on 19 March (Stressor 3(b) and 3(c); Tab 31).")
OC3=("The Appellant's evidence is that complaints from the public, from clinicians and from staff across the hospital arrived first at the Switchboard, by telephone and to the shared Switchboard inbox, and came to him as the operator on duty; that he triaged them and resolved a substantial proportion himself, escalating those that needed management action; and that complaints that were not resolved returned to the Switchboard to be dealt with again, including complaints about the currency of the on-call roster and the telephone directory. On the employer's own account, complaints about Switchboard operational errors were made directly to the Line Manager and managed solely by email or verbally with the complainant [¶ 267], and no change to the Switchboard's operating procedures as a consequence of any employee complaint is alleged before 30 June 2024. [¶ 272] These operating conditions are pleaded as the setting in which the causal particulars at 1(b), 1(h) and 1(k), and at Stressor 3(b), occurred. They are the Appellant's evidence, not admitted counts, and they are not pleaded as separate causal particulars.")
insert_after(d,'How critical the function is, as the Respondent admits.','The duty to consult, and the absence of any record of consultation.','The operating conditions: calls (context for the causal particulars). ',OC1)
insert_after(d,'The operating conditions: calls','The duty to consult, and the absence of any record of consultation.','Emergency codes, received and paged concurrently (context). ',OC2)
insert_after(d,'Emergency codes, received and paged concurrently','The duty to consult, and the absence of any record of consultation.','Complaints arriving at, and returning to, the Switchboard (context). ',OC3)
d.rep('The ordinary call load, and the Monday.','and it followed a break of seven hours. [¶ 284]','and it followed a break of seven hours. [¶ 284] The Appellant\'s evidence is that on that shift, after the short break, he managed the emergency codes and doctor pages through the SPOK paging system while fatigued.')
d.rep('2(e) Public holiday claim submitted late','2(e) Public holiday claim submitted late (30 March 2024). ',"2(e) Public holiday claim - Payroll's later account (30 March 2024). ")
set_body(d,"2(e) Public holiday claim - Payroll's later account","In its email to the Respondent of 11 July 2025, disclosed by the Respondent in July 2025, Payroll described the public holiday claim of 30 March 2024 as \"submitted late\" (Disclosure from witness conferencing - Qld Health Payroll, pp 2 to 3). This is relied on as Payroll's later account, not as an admission.")
d.rep('3(h) HR follow-up with the fatigue guideline','The Respondent disclosed the guideline, with that email chain, on 14 July 2025 (Tab 8A). The following passages are from that disclosed copy.',
 'The full guideline was disclosed with that email chain on 14 July 2025 and is identified separately in Schedule Part 2; Tab 8A is the cover page only. The following passages are from the disclosed guideline.')
d.rep('5A. The Respondent',"The Respondent's notified evidence is consistent with the admitted record.","The Respondent's notified lay evidence.")
d.rep('5A. The Respondent',"By particular, the outlines give no account of the dated events at Stressor 1(b), 1(f), 1(h) and 1(k), or at Stressor 3(e) to 3(h). On those particulars the facts are admitted,",
 "By particular, the outlines give no account of the dated events at Stressor 1(b), 1(f), 1(h) and 1(k), or at Stressor 3(e) and 3(f); nor of the internal records at Stressor 3(g) and 3(h), which are relied on only as proof of how the matters at 3(d) to 3(f) were handled. On the causal particulars, the facts are admitted,")
d.save()
print('ok')
# title: "PROPOSED SECOND AMENDED STATEMENT OF FACTS AND CONTENTIONS" applied separately
