# Letter: "How the admitted facts are relied on" (from paras 1 to 3 of the Appellant's letter to the Respondent of 9 Sep 2026);
# documentary sentence in "How the proposed Form 9A is arranged" shortened so the 9 Sep reference is made once.
exec(open('edit_change68.py').read().split("CAUSAL=")[0])
src=open('edit_change72.py').read(); exec(src[src.index('def set_body'):src.index('# ================= ELECTION')])
L=Doc('2026-10_LETTER_to_Registry_FINAL.docx')
L.rep('How the proposed Form 9A is arranged.'," As stated in the Appellant's letter to the Respondent of 9 September 2026, where the document is itself the step taken, the admission is relied on as establishing that the step was taken on the date and in the terms recorded.","")
insert_after(L,'How the proposed Form 9A is arranged.','The record, available on request.','How the admitted facts are relied on. ',
 "As stated in the Appellant's letter to the Respondent of 9 September 2026: the admissions are made for this proceeding only, under rule 49 of the Industrial Relations (Tribunals) Rules 2011, and relevance, admissibility and weight are for the Commission. Where an admitted document is itself the step taken - a directive issued by email, a roster as published, a payroll instruction or claim as recorded, a request as made and the reply as given - the admission is relied on as establishing that the step was taken on the date and in the terms recorded, and no characterisation, conclusion or inference is drawn from it beyond the fact admitted. Where an admitted document records the statement or opinion of another person, such as the treating practitioners' records or Review Decision 69983, it is relied on for its existence and wording; the treating practitioners will be called, and the review decision is relied on as the Regulator's own review, not as binding the Commission. Whether each event was management action, whether any management action was reasonable and taken in a reasonable way, and whether it contributed to the injury, are for the Commission to decide by applying the statutory test to those events.")
L.save(); print('ok')
